'\" t
.\"     Title: git-subdir
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 12/30/2016
.\"    Manual: Git Subdir Manual
.\"    Source: Git Subdir
.\"  Language: English
.\"
.TH "GIT\-SUBDIR" "1" "12/30/2016" "Git Subdir" "Git Subdir Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-subdir \- Integrate the content of a repository into a subdirectory
.SH "SYNOPSIS"
.sp
.nf
\fIgit subdir add\fR [\-b <branch>] [\-\-upstream\-branch <branch>] <repository> [<upstream\-repo>] <subdir>
\fIgit subdir fetch\fR [<subdir>\&...]
\fIgit subdir commit\fR[\-m <message] [\-\-dry\-run] <commit> [<subdir>]
\fIgit subdir branch\fR [\-b branch] [<subdir>]
\fIgit subdir update\fR [<subdir>]
\fIgit subdir push\fR [\-\-upstream] [\-\-dry\-run] [<subdir>]
\fIgit subdir status\fR [<subdir>\&...]
\fIgit subdir config\fR \-\-key <key> [\-\-value <value>] [\-\-unset] [<subdir>]
.fi
.SH "DESCRIPTION"
.sp
\fIgit subdir\fR maintains the content of an external Git repository within a subdirectory of your repository\&.
.sp
Local changes to the subdirectory can be filtered onto a branch and pushed back upstream\&. Long lived integration changes (such as to integrate an external project into your build system) are maintained on a branch and rebased each time you update to the latest upstream\&.
.sp
Developers can clone your project and freely commit changes to subdirectories without needing to know about or use \fIgit subdir\fR which can be considered a project maintainer\(cqs tool; only needed when re\-syncing a subdirectory\(cqs content with upstream\&.
.SH "COMMANDS"
.SS "add"
.sp
.if n \{\
.RS 4
.\}
.nf
\fIgit subdir add\fR [\-b <branch>] [\-\-upstream\-branch <branch>] [\-m <msg>]
                [\-\-pre\-integrated\-commit CORRESPONDING_COMMIT]
                <repository> [<upstream\-repository] <subdir>
.fi
.if n \{\
.RE
.\}
.sp
Creates a <subdir>/ directory containing a \&.git\-subdir/config file with a record of the corresponsing remote <repository> as well as (optionally) an upstream repository to monitor\&.
.sp
The <repository> would typically be a project\-specific fork of an upstream repository and is referred to as the \fIintegration\fR repository\&.
.sp
The benefit of specifying a second, upstream repository is that \fIgit subdir update\fR can streamline rebasing any project\-specific <subdir> changes onto the latest upstream changes\&.
.sp
Typically <subdir> wouldn\(cqt exist before running \fIgit subdir add\fR, but it\(cqs also possible to create a \&.git\-subdir/config file for a pre\-existing subdirectory (in which case \-\-pre\-integrated\-commit must be passed to identify a commit from <repository> that the subdirectory\(cqs content currently corresponds to)\&.
.sp
The initial <subdir> content will come from the <repository> branch if it already exists otherwise it will come from the <upstream\-repository>\&.
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBoptions\fR
.RS 4
.PP
\-q, \-\-quiet
.RS 4
Pass \-\-quiet to
\fIgit subdir fetch\fR
to silence other internally used git commands\&. Progress is not reported to the standard error stream\&.
.RE
.PP
\-v, \-\-verbose
.RS 4
Be verbose\&.
.RE
.PP
\-b, \-\-branch
.RS 4
The branch to fetch and maintain integration changes on\&. By default this is
\fImaster\fR
.RE
.PP
\-\-upstream\-branch
.RS 4
If an <upstream\-repository> has been specified then it\(cqs also possible to specify which upstream branch to monitor\&. By default this is
\fImaster\fR
.RE
.RE
.SS "fetch"
.sp
.if n \{\
.RS 4
.\}
.nf
\fIgit subdir fetch\fR [<subdir>]
.fi
.if n \{\
.RE
.\}
.sp
Fetches branches and tags from the configured \fIupstream\fR and \fIintegration\fR repositories
.sp
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBoptions\fR
.RS 4
.PP
\-q, \-\-quiet
.RS 4
Pass \-\-quiet to
\fIgit subdir fetch\fR
to silence other internally used git commands\&. Progress is not reported to the standard error stream\&.
.RE
.PP
\-v, \-\-verbose
.RS 4
Be verbose\&.
.RE
.RE
.SS "commit"
.sp
.if n \{\
.RS 4
.\}
.nf
\fIgit subdir commit\fR [\-m <msg>] [\-\-dry\-run] <commit> [<subdir>]
.fi
.if n \{\
.RE
.\}
.sp
Replaces the contents of <subdir> with the contents of <commit> in a single squashed commit\&. <commit> should be in the layout of the external repository\&.
.sp
If the <commit> is not an upstream commit it should then be pushed to the remote integration branch for others to be able to rebase your project\-specific changes onto different upstream versions\&. Running \fIgit subdir status\fR will try to warn when the last squashed <commit> doesn\(cqt appear to have been published for others\&. (See \fIgit subdir push\fR)
.sp
Note: it\(cqs ok to rebase these squash commits on a topic branch without confusing \fIgit subdir\fR, but it\(cqs recommended to avoid squashing extra changes into these commits, because commands like \fIgit subdir branch\fR you will split these extra changes back out into a separate, poorly named patch\&.
.sp
Note: Every time new content is squash committed to a subdirectory then \fIgit subdir\fR also creates a \fIref\fR for the commit whose content was used so that it can be referenced as a base for later \fIgit subdir\fR commands\&. These refs need to be published to your remote integration repo for other project maintainers too\&. (See \fIgit subdir push\fR)
.sp
Note: the extra squash commit references effectively connect the revision history of the subdirectory with that of the external project, but this connection is only preserved within the integration branch so users fetching your project don\(cqt also end up fetching the full history of these external projects\&. When the squash commit is first made then the reference is stored in <subdir>/\&.git\-subdir/refs and when pushed to your remote integration repo these are stored under \&.git/refs/git\-subdir/\&.
.SS "branch"
.sp
.if n \{\
.RS 4
.\}
.nf
\fIgit subdir branch\fR \-b <branch> [<subdir>]
.fi
.if n \{\
.RE
.\}
.sp
Creates a branch in the layout of the external project, and filters any patches that affect <subdir> onto this branch too\&. The branch is based on an upstream commit so it\(cqs possible to manually push changes upstream from here\&. Another use case might be to manually rebase on a more recent upstream before committing the result with \fIgit subdir commit\fR\&.
.SS "update"
.sp
.if n \{\
.RS 4
.\}
.nf
\fIgit subdir update\fR [<subdir>]
.fi
.if n \{\
.RE
.\}
.sp
This fetches from the configured upstream and integration repositories, then (if both branches have been configured) rebases integration changes on the latest upstream changes, rebases any local changes on top of this and then commits the result\&.
.sp
This is the recommended way to routinely pull in new upstream changes to <subdir>\&.
.sp
This is a convenience for the following steps:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
Running
\fIgit subdir fetch\fR
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
Running
\fIgit subdir branch\fR
to filter local <subdir> changes onto a branch based on your last subdirectory squash commit
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  3." 4.2
.\}
Running
\fIgit rebase\fR
to rebase that branch on the latest upstream or integration branch
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 4.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  4." 4.2
.\}
Running
\fIgit subdir commit\fR
to squash the result back into your current branch
.RE
.SS "status"
.sp
.if n \{\
.RS 4
.\}
.nf
\fIgit subdir status\fR [<subdir>\&...]
.fi
.if n \{\
.RE
.\}
.sp
Prints out the configuration for each <subdir>, including warnings about commits that have been integrated with \fIgit subdir commit\fR but have not yet been published for others\&.
.SS "config"
.sp
.if n \{\
.RS 4
.\}
.nf
\fIgit subdir config\fR \-\-key <key> [\-\-value <value>] [<subdir>]
\fIgit subdir config\fR \-\-key <key> [\-\-unset] [<subdir>]
.fi
.if n \{\
.RE
.\}
.sp
.if n \{\
.RS 4
.\}
.nf
examples:
  \fIgit subdir config\fR \-\-key upstream\&.url <subdir>
  \fIgit subdir config\fR \-\-key upstream\&.url \-\-value \m[blue]\fBhttps://foo\&.git\fR\m[] <subdir>
  \fIgit subdir config\fR \-\-key upstream\&.branch \-\-value foo <subdir>
  \fIgit subdir config\fR \-\-key upstream\&.branch \-\-unset <subdir>
  \fIgit subdir config\fR \-\-key integration\&.url <subdir>
.fi
.if n \{\
.RE
.\}
.sp
Note: this deviates from the standard \fIgit config\fR <option> [<value>] UI due to the ambiguity of <value> and <subdir> both being optional
.SH "EXAMPLE"
.sp
Lets say you have a container project \fIsuper\fR at \m[blue]\fBhttps://github\&.com/user/super\fR\m[] and another project \fIduper\fR at \m[blue]\fBhttps://github\&.com/upstream/duper\fR\m[] which you want to embed in the former\&.
.sp
The first thing to decide is where to maintain an \fIintegration\fR branch for any changes you might need to track for the \fIduper\fR subdirectory\&.
.sp
Lets assume you don\(cqt have privileges to touch the \fIupstream/duper\fR repo so you start by forking it and create \m[blue]\fBhttps://github\&.com/user/duper\fR\m[]\&. We\(cqll leave the master branch of this repo alone and create a \fIsuper\-integration\fR branch that we can push to \m[blue]\fBhttps://github\&.com/user/duper\fR\m[]\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ cd super/
$ git subdir add \-b super\-integration http://github\&.com/user/duper http://github\&.com/upstream/duper duper/
.fi
.if n \{\
.RE
.\}
.sp
Now make a local change to the duper/ subdirectory\&...
.sp
.if n \{\
.RS 4
.\}
.nf
$ echo "foo" > duper/file\&.txt
$ git commit \-m \*(Aqchange file\*(Aq duper/file\&.txt
.fi
.if n \{\
.RE
.\}
.sp
At this point the upstream may have improvements we want, while we still want to keep our change\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ git subdir update duper
.fi
.if n \{\
.RE
.\}
.sp
Will fetch the latest upstream, rebase the local change and commit the result back\&.
.sp
If you run \fIgit subdir status duper\fR now you will see a warning\&.
.sp
As part of this update your local change was rebased on upstream and \fIgit subdir status\fR is reminding you to push the rebased branch as your latest super\-integration branch\&.
.sp
Every time new contents are squash committed to a subdirectory (either via a \fIgit subdir commit\fR or a \fIgit subdir update\fR) then \fIgit subdir\fR also creates a \fIref\fR for the commit whose content was used so that the commit can always be used as a base for later \fIgit subdir\fR commands\&. In addition to the integration branch, these refs should be published for other project maintainers too\&. Note that these references effectively connect the revision history of the subdirectory with that of the external project, but this connection is only preserved within the integration branch so users fetching your project don\(cqt also end up fetching the full history of these external projects\&.
.sp
\fIgit subdir push\fR will push your integration branch (super\-integration) and commit refs to your configured integration repo:
.sp
.if n \{\
.RS 4
.\}
.nf
$ git subdir push duper
.fi
.if n \{\
.RE
.\}
.SH "CONFIGURATION"
.sp
\fIgit subdir\fR maintains the configuration for a subdirectory in a \&.git\-subdir/config file which is tracked as part of your repository history\&. These files are compatible with \fIgit config \-f \&.git\-subdir/config\fR and it\(cqs safe to modify (and commit) changes to \&.git\-subdir/config files with the exception that the \fIcommit\-uuid\fR line should not be touched since that will interfere with \fIgit subdir\fR identifying the changes that update the subdir contents\&.
.sp
\fIgit subdir\fR will create \fIsubdir\-upstream/<subdir>\fR and \fIsubdir\-integration/<subdir>\fR remotes in $GIT_DIR/ but never assumes these exist and always updates them before use based on the current \&.git\-subdir configuration\&.
.SH "COMPARED TO SIMILAR TOOLS"
.sp
\fIgit subdir\fR serves a similar purpose to git\-submodule(1), git\-subtree(1) so here are a few notes to help distinguish the tools\&.
.PP
\fIgit submodule\fR
.RS 4
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Developers cloning a repo that uses
\fIgit subdir\fR
don\(cqt need to know about or use
\fIgit subdir\fR\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIgit subdir\fR
incorporates external content via squash commits that themselves don\(cqt retain any history of the external project whereas
\fIgit submodule\fR
works as an assistant for cloning external git repositories within subdirectories of your project\&.
.RE
.RE
.PP
\fIgit subtree\fR
.RS 4
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
\fIgit subtree\fR
isn\(cqt designed to facilitate rebasing integration changes for an external repository and is generally geared around using merge commits to sync with upstream\&. For long lived integration changes, this may mean dealing with with conflicts without the original context of the changes when merging\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Similarly
\fIgit subtree\fR
doesn\(cqt have provisions for rebasing local, upstreamable changes\&.
.RE
.RE
.SH "LICENSE"
.sp
The MIT License
